### ISSUE TITLE
Not sure if i am missing something? 

### ISSUE THREAD

**Issue by brettcarr1** [isc-projects/dnsgen#1]
./dnsgen -i eth0 -a 192.168.1.243 -s 192.168.1.232 -l 30 -r 100000 -d dnsperf1fromukpcap.out

is returning no error but no operation just the "usage" statement, Am I missing a mandatory parameter?

Brett

**Comment by raybellis** [comment]
The `-m <macaddr>` parameter (destination MAC address ) is mandatory.

**Comment by raybellis** [comment]
I've slightly updated the usage text to make that stand out more.

(The use of raw sockets means that the code doesn't use the ARP and/or routing tables to send the packets, so you have to specify the mac address directly).
