### ISSUE TITLE
Use dnsgen report Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by xiejia1992** [isc-projects/dnsgen#2]
hello, raybellis: 

centos 7.7
Use as follows:
```
git clone https://github.com/isc-projects/dnsgen.git
cd dnsgen && make

echo "www.google.com A" > datafile.txt
./dnscvt datafile.txt

./dnsgen -i eno1 -a 192.168.1.2 -s 192.168.1.3 -m d8:9d:67:23:0b:d8 -l 30 -r 100000 -D datafile.raw
```
Then, return Segmentation fault (core dumped)

I don't know if it's a bug in dnsgen or my usage is incorrect

Can you tell me how should i use dnsgen ?

thinks

**Comment by raybellis** [comment]
It was a bug, triggered by using a much shorter input file than I ever did.

It's resolved with cb0c4a94afd0866fbb1a372f5888258897e0d7ce

Thanks for the report!
